function Hd = test5
%TEST5 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 07-Dec-2020 14:47:14

% IIR Comb Notching filter designed using the IIRCOMB function.

% All frequency values are in Hz.
Fs = 11035;  % Sampling Frequency

N     = 27;   % Order
BW    = 300;  % Bandwidth
Apass = 1;    % Bandwidth Attenuation

[b, a] = iircomb(N, BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
