function Hd = test6n1
%TEST6N1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 07-Dec-2020 14:53:39

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 11035;  % Sampling Frequency

Fnotch = 2002;  % Notch Frequency
BW     = 200;   % Bandwidth
Apass  = 1;     % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
