function Hd = f3bp1
%F3BP1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 09-Dec-2020 16:03:59

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 11035;  % Sampling Frequency

Fpass1 = 400;             % First Passband Frequency
Fstop1 = 425;             % First Stopband Frequency
Fstop2 = 606;             % Second Stopband Frequency
Fpass2 = 630;             % Second Passband Frequency
Dpass1 = 0.028774368332;  % First Passband Ripple
Dstop  = 0.001;           % Stopband Attenuation
Dpass2 = 0.057501127785;  % Second Passband Ripple
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
